"""
This type stub file was generated by pyright.
"""

_quotes = ...
_all_quotes = ...
class StringView:
    def __init__(self, buffer) -> None:
        ...
    
    @property
    def current(self): # -> None:
        ...
    
    @property
    def eof(self): # -> bool:
        ...
    
    def undo(self) -> None:
        ...
    
    def skip_ws(self): # -> bool:
        ...
    
    def skip_string(self, string) -> bool:
        ...
    
    def read_rest(self):
        ...
    
    def read(self, n):
        ...
    
    def get(self): # -> None:
        ...
    
    def get_word(self):
        ...
    
    def get_quoted_word(self): # -> LiteralString | None:
        ...
    
    def __repr__(self) -> str:
        ...
    


