"""
This type stub file was generated by pyright.
"""

from .async_ import *
from .sync import *

"""
nextcord.webhook
~~~~~~~~~~~~~~~~

Webhook support

:copyright: (c) 2015-2021 Rapptz
:copyright: (c) 2021-present Nextcord Developers
:license: MIT, see LICENSE for more details.
"""
