repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: local
    hooks:
      - id: no-symlinks
        name: no symlinks
        description: "check for symlinks"
        entry: "symlinks may not be committed due to platform support"
        language: fail
        types: [symlink]

      - id: spdx-licensing
        name: spdx license identifiers
        description: check for the SPDX-License-Identifier in each file.
        language: pygrep
        entry: 'SPDX-License-Identifier: '
        args: [--negate]
        types: [text]
        exclude: 'LICENSE|pdm.lock'

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        name: "run isort"

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        name: "run black"

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.254
    hooks:
      - id: ruff
        name: "run ruff"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: local
    hooks:
      - id: no-symlinks
        name: no symlinks
        description: "Check for symlinks"
        entry: "symlinks may not be committed due to platform support"
        language: fail
        types: [symlink]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        name: "run isort"

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        name: "run black"

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.254
    hooks:
      - id: ruff
        name: "run ruff"
