[project]
name = "dispatcher"
description = "An extension to easily dispatch custom events for discord bots."
authors = [
    { name = "Snipy7374", email = "snipy7374@gmail.com" },
]
dependencies = [
    "Jinja2>=3.1.2",
]
requires-python = ">=3.8"
readme = "README.md"
license = { text = "MIT" }
dynamic = ["version"]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pyright]
typeCheckingMode = "strict"
reportInvalidStringEscapeSequence = false
reportUnusedImport = false
reportUnknownParameterType = false
reportUnknownArgumentType = false
reportUnknownMemberType = false
reportMissingParameterType = false
reportUnnecessaryIsInstance = false

[tool.black]
line-length = 100
target-version = ["py38", "py39", "py310", "py311"]

[tool.isort]
profile = "black"
py_version = 38
line_length = 100

[tool.ruff]
line-length = 100
target-version = "py38"
ignore = [
    "F403", # Star imports
]

[tool.pdm.dev-dependencies]
dev = [
    "pre-commit>=3.1.1",
]

[tool.pdm.scripts]
setup_env = "pre-commit install"
