"""
This type stub file was generated by pyright.
"""

from typing import NamedTuple, Optional, TYPE_CHECKING
from .user import User

__all__ = ("BanEntry", )
if TYPE_CHECKING:
    ...
class BanEntry(NamedTuple):
    reason: Optional[str]
    user: User
    ...


