"""
This type stub file was generated by pyright.
"""

import struct
from typing import ClassVar, Generator, IO, TYPE_CHECKING, Tuple
from .errors import DiscordException

__all__ = ("OggError", "OggPage", "OggStream")
class OggError(DiscordException):
    """An exception that is thrown for Ogg stream parsing errors."""
    ...


class OggPage:
    _header: ClassVar[struct.Struct] = ...
    if TYPE_CHECKING:
        flag: int
        gran_pos: int
        serial: int
        pagenum: int
        crc: int
        segnum: int
        ...
    def __init__(self, stream: IO[bytes]) -> None:
        ...
    
    def iter_packets(self) -> Generator[Tuple[bytes, bool], None, None]:
        ...
    


class OggStream:
    def __init__(self, stream: IO[bytes]) -> None:
        ...
    
    def iter_packets(self) -> Generator[bytes, None, None]:
        ...
    


