"""
This type stub file was generated by pyright.
"""

from typing import Dict, Optional
from typing_extensions import Self
from .enums import RoleConnectionMetadataType
from .types.role_connections import ApplicationRoleConnectionMetadata as RoleConnectionMetadataPayload

__all__ = ("RoleConnectionMetadata", )
class RoleConnectionMetadata:
    """Represents a role connection metadata object.

    .. versionadded:: 2.4

    Attributes
    ----------
    type: :class:`RoleConnectionMetadataType`
        The type of metadata value.
    key: :class:`str`
        The dictionary key for the metadata field.
    name: :class:`str`
        The name of the metadata field.
    name_localizations: Optional[:class:`dict`]
        The translations of the name.
    description: :class:`str`
        The description of the metadata field.
    description_localizations: Optional[:class:`dict`]
        The translations of the description.
    """
    __slots__ = ...
    def __init__(self, *, type: RoleConnectionMetadataType, key: str, name: str, name_localizations: Optional[Dict[str, str]], description: str, description_localizations: Optional[Dict[str, str]]) -> None:
        ...
    
    @classmethod
    def from_data(cls, data: RoleConnectionMetadataPayload) -> Self:
        ...
    
    def __repr__(self) -> str:
        ...
    


