"""
This type stub file was generated by pyright.
"""

"""
Aliased moodule. See the same file in the nextcord folder for more information
Autogenerated by aliasgen.py
"""
__all__ = ("Attachment", "Message", "PartialMessage", "MessageReference", "DeletedReferencedMessage")
