"""
This type stub file was generated by pyright.
"""

"""
Aliased moodule. See the same file in the nextcord folder for more information
Autogenerated by aliasgen.py
"""
__all__ = ("oauth_url", "snowflake_time", "time_snowflake", "find", "get", "sleep_until", "utcnow", "remove_markdown", "escape_markdown", "escape_mentions", "parse_raw_mentions", "parse_raw_role_mentions", "parse_raw_channel_mentions", "as_chunks", "format_dt")
