"""
This type stub file was generated by pyright.
"""

from typing import Callable, Generic, List, Optional, TYPE_CHECKING, Tuple, TypeVar
from ...components import RoleSelectMenu
from ...interactions import ClientT
from ...role import Role
from ...state import ConnectionState
from ..item import ItemCallbackType
from .base import SelectBase, SelectValuesBase
from typing_extensions import Self
from ...guild import Guild
from ...types.components import RoleSelectMenu as RoleSelectMenuPayload
from ...types.interactions import ComponentInteractionData

if TYPE_CHECKING:
    ...
__all__ = ("RoleSelect", "role_select", "RoleSelectValues")
V = TypeVar("V", bound="View", covariant=True)
class RoleSelectValues(SelectValuesBase):
    """Represents the values of a :class:`.ui.RoleSelect`."""
    @property
    def roles(self) -> List[Role]:
        """List[:class:`.Role`]: The roles that were selected."""
        ...
    


class RoleSelect(SelectBase, Generic[V]):
    """Represents a UI role select menu.

    This is usually represented as a drop down menu.

    In order to get the selected items that the user has chosen,
    use :attr:`RoleSelect.values`.

    .. versionadded:: 2.3

    Parameters
    ------------
    custom_id: :class:`str`
        The ID of the select menu that gets received during an interaction.
        If not given then one is generated for you.
    placeholder: Optional[:class:`str`]
        The placeholder text that is shown if nothing is selected, if any.
    min_values: :class:`int`
        The minimum number of items that must be chosen for this select menu.
        Defaults to 1 and must be between 1 and 25.
    max_values: :class:`int`
        The maximum number of items that must be chosen for this select menu.
        Defaults to 1 and must be between 1 and 25.
    disabled: :class:`bool`
        Whether the select is disabled or not. Defaults to ``False``.
    row: Optional[:class:`int`]
        The relative row this select menu belongs to. A Discord component can only have 5
        rows. By default, items are arranged automatically into those 5 rows. If you'd
        like to control the relative positioning of the row then passing an index is advised.
        For example, row=1 will show up before row=2. Defaults to ``None``, which is automatic
        ordering. The row number must be between 0 and 4 (i.e. zero indexed).
    """
    __item_repr_attributes__: Tuple[str, ...] = ...
    def __init__(self, *, custom_id: str = ..., placeholder: Optional[str] = ..., min_values: int = ..., max_values: int = ..., disabled: bool = ..., row: Optional[int] = ...) -> None:
        ...
    
    @property
    def values(self) -> RoleSelectValues:
        """:class:`.ui.RoleSelectValues`: A list of :class:`.Role` that have been selected by the user."""
        ...
    
    def to_component_dict(self) -> RoleSelectMenuPayload:
        ...
    
    @classmethod
    def from_component(cls, component: RoleSelectMenu) -> Self:
        ...
    
    def refresh_state(self, data: ComponentInteractionData, state: ConnectionState, guild: Optional[Guild]) -> None:
        ...
    


def role_select(*, placeholder: Optional[str] = ..., custom_id: str = ..., min_values: int = ..., max_values: int = ..., disabled: bool = ..., row: Optional[int] = ...) -> Callable[[ItemCallbackType[RoleSelect[V], ClientT]], ItemCallbackType[RoleSelect[V], ClientT]]:
    """A decorator that attaches a role select menu to a component.

    The function being decorated should have three parameters, ``self`` representing
    the :class:`.ui.View`, the :class:`.ui.RoleSelect` being pressed and
    the :class:`.Interaction` you receive.

    In order to get the selected items that the user has chosen within the callback
    use :attr:`RoleSelect.values`.

    .. versionadded:: 2.3

    Parameters
    ----------
    placeholder: Optional[:class:`str`]
        The placeholder text that is shown if nothing is selected, if any.
    custom_id: :class:`str`
        The ID of the select menu that gets received during an interaction.
        It is recommended not to set this parameter to prevent conflicts.
    row: Optional[:class:`int`]
        The relative row this select menu belongs to. A Discord component can only have 5
        rows. By default, items are arranged automatically into those 5 rows. If you'd
        like to control the relative positioning of the row then passing an index is advised.
        For example, row=1 will show up before row=2. Defaults to ``None``, which is automatic
        ordering. The row number must be between 0 and 4 (i.e. zero indexed).
    min_values: :class:`int`
        The minimum number of items that must be chosen for this select menu.
        Defaults to 1 and must be between 1 and 25.
    max_values: :class:`int`
        The maximum number of items that must be chosen for this select menu.
        Defaults to 1 and must be between 1 and 25.
    disabled: :class:`bool`
        Whether the select is disabled or not. Defaults to ``False``.
    """
    ...

