"""
This type stub file was generated by pyright.
"""

"""
Aliased moodule. See the same file in the nextcord folder for more information
Autogenerated by aliasgen.py
"""
__all__ = ("Converter", "ObjectConverter", "MemberConverter", "UserConverter", "MessageConverter", "PartialMessageConverter", "TextChannelConverter", "InviteConverter", "GuildConverter", "RoleConverter", "GameConverter", "ColourConverter", "ColorConverter", "VoiceChannelConverter", "StageChannelConverter", "EmojiConverter", "PartialEmojiConverter", "CategoryChannelConverter", "IDConverter", "ThreadConverter", "GuildChannelConverter", "GuildStickerConverter", "clean_content", "Greedy", "run_converters")
