"""
This type stub file was generated by pyright.
"""

"""
Aliased moodule. See the same file in the nextcord folder for more information
Autogenerated by aliasgen.py
"""
__all__ = ("Command", "Group", "GroupMixin", "command", "group", "has_role", "has_permissions", "has_any_role", "check", "check_any", "before_invoke", "after_invoke", "bot_has_role", "bot_has_permissions", "bot_has_any_role", "cooldown", "dynamic_cooldown", "max_concurrency", "dm_only", "guild_only", "is_owner", "is_nsfw", "has_guild_permissions", "bot_has_guild_permissions")
