"""
This type stub file was generated by pyright.
"""

"""
Aliased moodule. See the same file in the nextcord folder for more information
Autogenerated by aliasgen.py
"""
__all__ = ("CommandError", "MissingRequiredArgument", "BadArgument", "PrivateMessageOnly", "NoPrivateMessage", "CheckFailure", "CheckAnyFailure", "CommandNotFound", "DisabledCommand", "CommandInvokeError", "TooManyArguments", "UserInputError", "CommandOnCooldown", "MaxConcurrencyReached", "NotOwner", "MessageNotFound", "ObjectNotFound", "MemberNotFound", "GuildNotFound", "UserNotFound", "ChannelNotFound", "ThreadNotFound", "ChannelNotReadable", "BadColourArgument", "BadColorArgument", "RoleNotFound", "BadInviteArgument", "EmojiNotFound", "GuildStickerNotFound", "PartialEmojiConversionFailure", "BadBoolArgument", "MissingRole", "BotMissingRole", "MissingAnyRole", "BotMissingAnyRole", "MissingPermissions", "BotMissingPermissions", "NSFWChannelRequired", "ConversionError", "BadUnionArgument", "BadLiteralArgument", "ArgumentParsingError", "UnexpectedQuoteError", "InvalidEndOfQuotedStringError", "ExpectedClosingQuoteError", "ExtensionError", "ExtensionAlreadyLoaded", "ExtensionNotLoaded", "NoEntryPointError", "ExtensionFailed", "ExtensionNotFound", "CommandRegistrationError", "FlagError", "BadFlagArgument", "MissingFlagArgument", "TooManyFlags", "MissingRequiredFlag")
